export const WEBMCP_PARITY_TOOL_NAMES = [
	"list_resumes",
	"list_resume_tags",
	"read_resume",
	"download_resume_pdf",
	"create_resume",
	"import_resume",
	"duplicate_resume",
	"apply_resume_patch",
	"update_resume",
	"delete_resume",
	"lock_resume",
	"unlock_resume",
	"get_resume_statistics",
	"list_applications",
	"read_application",
	"list_application_tags",
	"get_application_stats",
	"create_application",
	"update_application",
	"add_application_note",
	"update_application_timeline_entry",
	"delete_application_timeline_entry",
	"delete_application",
	"bulk_update_applications",
	"bulk_delete_applications",
	"import_applications",
	"attach_application_document",
	"remove_application_document",
	"autofill_application_from_job",
	"score_application_match",
	"tailor_resume_for_application",
	"draft_application_message",
] as const;

export type WebMcpParityToolName = (typeof WEBMCP_PARITY_TOOL_NAMES)[number];
